casper.start('http://localhost:3000/', function () {
  this.echo(this.getTitle());
  this.capture('home.jpg', undefined, {
    format: 'jpg',
    quality: 75
  });
});

casper.test.begin('Home page should have a title', 2, function (test) {
  casper.start("http://localhost:3000/", function () {
    test.assertTitle("Express");
    test.assertExists('h1', 'Content generated by React')
  })

  casper.run();
});

